server.port=8081
db.url=jdbc:mysql://localhost:3306/patientdb
db.username=root

message=Welcome to the Patient Service! This service manages patient records and provides APIs for CRUD operations. Please ensure that you have the necessary permissions to access patient data.